### ISSUE TITLE
URL Imports from external url get replaced

### ISSUE THREAD

**Issue by sense-design** [SebastianM/grunt-fscss#9]
Code

    @import url(//fonts.googleapis.com/css?family=Open+Sans);

gets

    @import url($CMS_REF(media:"css")$?family=Open+Sans);

Would be nice if this would be excluded also

**Comment by SebastianM** [comment]
@sense-design Thanks, that's definitely useful.
Can you open a PR in this project and add a test for that?

Thanks

**Comment by SebastianM** [comment]
Thanks, landed as a383793
